language: python
python:
  - 2.7.13

dist: trusty

addons:
  chrome: stable

#before_install:
#  - # start your web application and listen on `localhost`
#  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

env:
  - DJANGO=1.11.12 DB=sqlite WEBDRIVER=~/chromedriver

install:
  - curl -Lk https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip -o ~/chromedriver_linux64.zip
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo chmod +x ~/chromedriver
  - pip install -r requirements.txt

script:
  - python manage.py migrate
  - python manage.py test

after_success:
  - coverage run --source=. manage.py test --noinput
  - coveralls



